/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AidRecipient {
  'id' : bigint,
  'nik' : string,
  'name' : string,
  'district' : string,
  'aidType' : string,
  'address' : string,
  'aidAmount' : bigint,
  'registrationDate' : bigint,
  'distributionStatus' : string,
  'subdistrict' : string,
}
export interface Publication {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : bigint,
  'summary' : string,
}
export interface Report {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'topic' : string,
  'reporterName' : string,
  'description' : string,
  'reportDate' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAidRecipient' : ActorMethod<[AidRecipient], bigint>,
  'addPublication' : ActorMethod<[Publication], bigint>,
  'addReport' : ActorMethod<[Report], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAidRecipient' : ActorMethod<[bigint], boolean>,
  'deletePublication' : ActorMethod<[bigint], boolean>,
  'filterAidRecipientsByDistrict' : ActorMethod<[string], Array<AidRecipient>>,
  'filterAidRecipientsByStatus' : ActorMethod<[string], Array<AidRecipient>>,
  'filterAidRecipientsByType' : ActorMethod<[string], Array<AidRecipient>>,
  'filterReportsByStatus' : ActorMethod<[string], Array<Report>>,
  'filterReportsByTopic' : ActorMethod<[string], Array<Report>>,
  'getAidRecipientById' : ActorMethod<[bigint], [] | [AidRecipient]>,
  'getAllAidRecipients' : ActorMethod<[], Array<AidRecipient>>,
  'getAllPublications' : ActorMethod<[], Array<Publication>>,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublicationById' : ActorMethod<[bigint], [] | [Publication]>,
  'getRecipientsByAidType' : ActorMethod<[], Array<[string, bigint]>>,
  'getRecipientsByDistrict' : ActorMethod<[], Array<[string, bigint]>>,
  'getRecipientsByStatus' : ActorMethod<[], Array<[string, bigint]>>,
  'getReportById' : ActorMethod<[bigint], [] | [Report]>,
  'getReportsByStatus' : ActorMethod<[], Array<[string, bigint]>>,
  'getReportsByTopic' : ActorMethod<[], Array<[string, bigint]>>,
  'getTotalRecipients' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAidRecipients' : ActorMethod<[string], Array<AidRecipient>>,
  'updateAidRecipient' : ActorMethod<[AidRecipient], boolean>,
  'updatePublication' : ActorMethod<[Publication], boolean>,
  'updateReportStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];