/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AidRecipient = IDL.Record({
  'id' : IDL.Nat,
  'nik' : IDL.Text,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'aidType' : IDL.Text,
  'address' : IDL.Text,
  'aidAmount' : IDL.Nat,
  'registrationDate' : IDL.Int,
  'distributionStatus' : IDL.Text,
  'subdistrict' : IDL.Text,
});
export const Publication = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'summary' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'reporterName' : IDL.Text,
  'description' : IDL.Text,
  'reportDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAidRecipient' : IDL.Func([AidRecipient], [IDL.Nat], []),
  'addPublication' : IDL.Func([Publication], [IDL.Nat], []),
  'addReport' : IDL.Func([Report], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAidRecipient' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePublication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'filterAidRecipientsByDistrict' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AidRecipient)],
      ['query'],
    ),
  'filterAidRecipientsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AidRecipient)],
      ['query'],
    ),
  'filterAidRecipientsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AidRecipient)],
      ['query'],
    ),
  'filterReportsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
  'filterReportsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
  'getAidRecipientById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AidRecipient)],
      ['query'],
    ),
  'getAllAidRecipients' : IDL.Func([], [IDL.Vec(AidRecipient)], ['query']),
  'getAllPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicationById' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
  'getRecipientsByAidType' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getRecipientsByDistrict' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getRecipientsByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getReportById' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getReportsByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getReportsByTopic' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTotalRecipients' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAidRecipients' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AidRecipient)],
      ['query'],
    ),
  'updateAidRecipient' : IDL.Func([AidRecipient], [IDL.Bool], []),
  'updatePublication' : IDL.Func([Publication], [IDL.Bool], []),
  'updateReportStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AidRecipient = IDL.Record({
    'id' : IDL.Nat,
    'nik' : IDL.Text,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'aidType' : IDL.Text,
    'address' : IDL.Text,
    'aidAmount' : IDL.Nat,
    'registrationDate' : IDL.Int,
    'distributionStatus' : IDL.Text,
    'subdistrict' : IDL.Text,
  });
  const Publication = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'summary' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'reporterName' : IDL.Text,
    'description' : IDL.Text,
    'reportDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAidRecipient' : IDL.Func([AidRecipient], [IDL.Nat], []),
    'addPublication' : IDL.Func([Publication], [IDL.Nat], []),
    'addReport' : IDL.Func([Report], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAidRecipient' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePublication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'filterAidRecipientsByDistrict' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AidRecipient)],
        ['query'],
      ),
    'filterAidRecipientsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AidRecipient)],
        ['query'],
      ),
    'filterAidRecipientsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AidRecipient)],
        ['query'],
      ),
    'filterReportsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'filterReportsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
    'getAidRecipientById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AidRecipient)],
        ['query'],
      ),
    'getAllAidRecipients' : IDL.Func([], [IDL.Vec(AidRecipient)], ['query']),
    'getAllPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicationById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Publication)],
        ['query'],
      ),
    'getRecipientsByAidType' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getRecipientsByDistrict' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getRecipientsByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getReportById' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getReportsByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getReportsByTopic' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTotalRecipients' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAidRecipients' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AidRecipient)],
        ['query'],
      ),
    'updateAidRecipient' : IDL.Func([AidRecipient], [IDL.Bool], []),
    'updatePublication' : IDL.Func([Publication], [IDL.Bool], []),
    'updateReportStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };