/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserEntry {
    principal: Principal;
    role: string;
}
export interface ValidationStats {
    byValidationStatus: Array<[string, bigint]>;
    totalVictims: bigint;
    byDisasterType: Array<[string, bigint]>;
}
export interface DisasterVictim {
    id: bigint;
    rt: string;
    rw: string;
    nik: string;
    kabupaten: string;
    fullName: string;
    lossDescription: string;
    disasterDate: bigint;
    kecamatan: string;
    address: string;
    disasterType: string;
    physicalCondition: string;
    registrationDate: bigint;
    damageLevel: string;
    registeredBy: Principal;
    kelurahan: string;
}
export interface ValidationRecord {
    id: bigint;
    validationStatus: string;
    victimId: bigint;
    needType: string;
    needDescription: string;
    createdBy: Principal;
    createdDate: bigint;
    validatorNotes: string;
    estimatedValue: bigint;
    validationDate?: bigint;
    validatedBy?: Principal;
}
export interface AidRecipient {
    id: bigint;
    nik: string;
    name: string;
    district: string;
    aidType: string;
    address: string;
    aidAmount: bigint;
    registrationDate: bigint;
    distributionStatus: string;
    subdistrict: string;
}
export interface Publication {
    id: bigint;
    title: string;
    content: string;
    publishDate: bigint;
    tags: Array<string>;
    author: string;
    readTime: bigint;
    summary: string;
}
export interface BantuanPenerima {
    id: bigint;
    nik: string;
    updatedDate: bigint;
    tindakLanjutKeterangan: string;
    alamat: string;
    nama: string;
    createdBy: Principal;
    createdDate: bigint;
    instansiPembantu: string;
    keterangan: string;
    validasiStatus: string;
    prosesTindakLanjut: string;
    keperluanBantuan: string;
}
export interface Report {
    id: bigint;
    status: string;
    title: string;
    topic: string;
    reporterName: string;
    description: string;
    reportDate: bigint;
}
export interface FooterLink {
    id: bigint;
    url: string;
    linkLabel: string;
    order: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAidRecipient(aid: AidRecipient): Promise<bigint>;
    addBantuanPenerima(data: BantuanPenerima): Promise<void>;
    addDisasterVictim(victim: DisasterVictim): Promise<bigint>;
    addFooterLink(link: FooterLink): Promise<bigint>;
    addPublication(publication: Publication): Promise<bigint>;
    addReport(report: Report): Promise<bigint>;
    addValidationRecord(record: ValidationRecord): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignValidatorRole(user: Principal): Promise<void>;
    deleteAidRecipient(id: bigint): Promise<boolean>;
    deleteBantuanPenerima(id: bigint): Promise<boolean>;
    deleteDisasterVictim(id: bigint): Promise<void>;
    deleteFooterLink(id: bigint): Promise<boolean>;
    deletePublication(id: bigint): Promise<boolean>;
    deleteReport(id: bigint): Promise<boolean>;
    deleteValidationRecord(id: bigint): Promise<void>;
    filterAidRecipientsByDistrict(district: string): Promise<Array<AidRecipient>>;
    filterAidRecipientsByStatus(status: string): Promise<Array<AidRecipient>>;
    filterAidRecipientsByType(aidType: string): Promise<Array<AidRecipient>>;
    filterBantuanPenerimaByStatus(status: string): Promise<Array<BantuanPenerima>>;
    filterReportsByStatus(status: string): Promise<Array<Report>>;
    filterReportsByTopic(topic: string): Promise<Array<Report>>;
    getAidRecipientById(id: bigint): Promise<AidRecipient | null>;
    getAllAidRecipients(): Promise<Array<AidRecipient>>;
    getAllBantuanPenerima(): Promise<Array<BantuanPenerima>>;
    getAllDisasterVictims(): Promise<Array<DisasterVictim>>;
    getAllPublications(): Promise<Array<Publication>>;
    getAllReports(): Promise<Array<Report>>;
    getAllUsers(): Promise<Array<UserEntry>>;
    getAllValidationRecords(): Promise<Array<ValidationRecord>>;
    getAllValidators(): Promise<Array<Principal>>;
    getBantuanPenerimaById(id: bigint): Promise<BantuanPenerima | null>;
    getCallerUserProfile(): Promise<{
        name: string;
    } | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDisasterVictimById(id: bigint): Promise<DisasterVictim | null>;
    getFooterLinks(): Promise<Array<FooterLink>>;
    getPublicationById(id: bigint): Promise<Publication | null>;
    getRecipientsByAidType(): Promise<Array<[string, bigint]>>;
    getRecipientsByDistrict(): Promise<Array<[string, bigint]>>;
    getRecipientsByStatus(): Promise<Array<[string, bigint]>>;
    getReportById(id: bigint): Promise<Report | null>;
    getReportsByStatus(): Promise<Array<[string, bigint]>>;
    getReportsByTopic(): Promise<Array<[string, bigint]>>;
    getTotalRecipients(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<{
        name: string;
    } | null>;
    getValidationRecordsByVictim(victimId: bigint): Promise<Array<ValidationRecord>>;
    getValidationStats(): Promise<ValidationStats>;
    initializeSampleData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAdminOrValidator(): Promise<boolean>;
    isCallerValidator(): Promise<boolean>;
    revokeValidatorRole(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: {
        name: string;
    }): Promise<void>;
    searchAidRecipients(searchTerm: string): Promise<Array<AidRecipient>>;
    updateAidRecipient(aid: AidRecipient): Promise<boolean>;
    updateBantuanPenerima(data: BantuanPenerima): Promise<void>;
    updateBantuanPenerimaStatus(id: bigint, validasiStatus: string, tindakLanjutKeterangan: string, instansiPembantu: string): Promise<void>;
    updateDisasterVictim(victim: DisasterVictim): Promise<boolean>;
    updateFooterLink(link: FooterLink): Promise<boolean>;
    updatePublication(publication: Publication): Promise<boolean>;
    updateReportStatus(id: bigint, status: string): Promise<boolean>;
    updateValidationRecord(record: ValidationRecord): Promise<boolean>;
    updateValidationStatus(id: bigint, status: string, notes: string, validatedBy: Principal): Promise<boolean>;
}
import type { AidRecipient as _AidRecipient, BantuanPenerima as _BantuanPenerima, DisasterVictim as _DisasterVictim, Publication as _Publication, Report as _Report, UserRole as _UserRole, ValidationRecord as _ValidationRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAidRecipient(arg0: AidRecipient): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAidRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAidRecipient(arg0);
            return result;
        }
    }
    async addBantuanPenerima(arg0: BantuanPenerima): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBantuanPenerima(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBantuanPenerima(arg0);
            return result;
        }
    }
    async addDisasterVictim(arg0: DisasterVictim): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDisasterVictim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDisasterVictim(arg0);
            return result;
        }
    }
    async addFooterLink(arg0: FooterLink): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFooterLink(arg0);
            return result;
        }
    }
    async addPublication(arg0: Publication): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPublication(arg0);
            return result;
        }
    }
    async addReport(arg0: Report): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReport(arg0);
            return result;
        }
    }
    async addValidationRecord(arg0: ValidationRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addValidationRecord(to_candid_ValidationRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addValidationRecord(to_candid_ValidationRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignValidatorRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignValidatorRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignValidatorRole(arg0);
            return result;
        }
    }
    async deleteAidRecipient(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAidRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAidRecipient(arg0);
            return result;
        }
    }
    async deleteBantuanPenerima(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBantuanPenerima(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBantuanPenerima(arg0);
            return result;
        }
    }
    async deleteDisasterVictim(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDisasterVictim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDisasterVictim(arg0);
            return result;
        }
    }
    async deleteFooterLink(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFooterLink(arg0);
            return result;
        }
    }
    async deletePublication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublication(arg0);
            return result;
        }
    }
    async deleteReport(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async deleteValidationRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteValidationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteValidationRecord(arg0);
            return result;
        }
    }
    async filterAidRecipientsByDistrict(arg0: string): Promise<Array<AidRecipient>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAidRecipientsByDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAidRecipientsByDistrict(arg0);
            return result;
        }
    }
    async filterAidRecipientsByStatus(arg0: string): Promise<Array<AidRecipient>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAidRecipientsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAidRecipientsByStatus(arg0);
            return result;
        }
    }
    async filterAidRecipientsByType(arg0: string): Promise<Array<AidRecipient>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAidRecipientsByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAidRecipientsByType(arg0);
            return result;
        }
    }
    async filterBantuanPenerimaByStatus(arg0: string): Promise<Array<BantuanPenerima>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBantuanPenerimaByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBantuanPenerimaByStatus(arg0);
            return result;
        }
    }
    async filterReportsByStatus(arg0: string): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReportsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReportsByStatus(arg0);
            return result;
        }
    }
    async filterReportsByTopic(arg0: string): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReportsByTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReportsByTopic(arg0);
            return result;
        }
    }
    async getAidRecipientById(arg0: bigint): Promise<AidRecipient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAidRecipientById(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAidRecipientById(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAidRecipients(): Promise<Array<AidRecipient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAidRecipients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAidRecipients();
            return result;
        }
    }
    async getAllBantuanPenerima(): Promise<Array<BantuanPenerima>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBantuanPenerima();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBantuanPenerima();
            return result;
        }
    }
    async getAllDisasterVictims(): Promise<Array<DisasterVictim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDisasterVictims();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDisasterVictims();
            return result;
        }
    }
    async getAllPublications(): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublications();
            return result;
        }
    }
    async getAllReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllValidationRecords(): Promise<Array<ValidationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllValidationRecords();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllValidationRecords();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllValidators(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllValidators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllValidators();
            return result;
        }
    }
    async getBantuanPenerimaById(arg0: bigint): Promise<BantuanPenerima | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBantuanPenerimaById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBantuanPenerimaById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<{
        name: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDisasterVictimById(arg0: bigint): Promise<DisasterVictim | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisasterVictimById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisasterVictimById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFooterLinks(): Promise<Array<FooterLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFooterLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFooterLinks();
            return result;
        }
    }
    async getPublicationById(arg0: bigint): Promise<Publication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicationById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicationById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipientsByAidType(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipientsByAidType();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipientsByAidType();
            return result;
        }
    }
    async getRecipientsByDistrict(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipientsByDistrict();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipientsByDistrict();
            return result;
        }
    }
    async getRecipientsByStatus(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipientsByStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipientsByStatus();
            return result;
        }
    }
    async getReportById(arg0: bigint): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByStatus(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByStatus();
            return result;
        }
    }
    async getReportsByTopic(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByTopic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByTopic();
            return result;
        }
    }
    async getTotalRecipients(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRecipients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRecipients();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<{
        name: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValidationRecordsByVictim(arg0: bigint): Promise<Array<ValidationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidationRecordsByVictim(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidationRecordsByVictim(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValidationStats(): Promise<ValidationStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidationStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidationStats();
            return result;
        }
    }
    async initializeSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSampleData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAdminOrValidator(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdminOrValidator();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdminOrValidator();
            return result;
        }
    }
    async isCallerValidator(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerValidator();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerValidator();
            return result;
        }
    }
    async revokeValidatorRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeValidatorRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeValidatorRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: {
        name: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAidRecipients(arg0: string): Promise<Array<AidRecipient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAidRecipients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAidRecipients(arg0);
            return result;
        }
    }
    async updateAidRecipient(arg0: AidRecipient): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAidRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAidRecipient(arg0);
            return result;
        }
    }
    async updateBantuanPenerima(arg0: BantuanPenerima): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBantuanPenerima(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBantuanPenerima(arg0);
            return result;
        }
    }
    async updateBantuanPenerimaStatus(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBantuanPenerimaStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBantuanPenerimaStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDisasterVictim(arg0: DisasterVictim): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisasterVictim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisasterVictim(arg0);
            return result;
        }
    }
    async updateFooterLink(arg0: FooterLink): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFooterLink(arg0);
            return result;
        }
    }
    async updatePublication(arg0: Publication): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublication(arg0);
            return result;
        }
    }
    async updateReportStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, arg1);
            return result;
        }
    }
    async updateValidationRecord(arg0: ValidationRecord): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateValidationRecord(to_candid_ValidationRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateValidationRecord(to_candid_ValidationRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateValidationStatus(arg0: bigint, arg1: string, arg2: string, arg3: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateValidationStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateValidationStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationRecord_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationRecord): ValidationRecord {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BantuanPenerima]): BantuanPenerima | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        name: string;
    }]): {
    name: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DisasterVictim]): DisasterVictim | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Publication]): Publication | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AidRecipient]): AidRecipient | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    validationStatus: string;
    victimId: bigint;
    needType: string;
    needDescription: string;
    createdBy: Principal;
    createdDate: bigint;
    validatorNotes: string;
    estimatedValue: bigint;
    validationDate: [] | [bigint];
    validatedBy: [] | [Principal];
}): {
    id: bigint;
    validationStatus: string;
    victimId: bigint;
    needType: string;
    needDescription: string;
    createdBy: Principal;
    createdDate: bigint;
    validatorNotes: string;
    estimatedValue: bigint;
    validationDate?: bigint;
    validatedBy?: Principal;
} {
    return {
        id: value.id,
        validationStatus: value.validationStatus,
        victimId: value.victimId,
        needType: value.needType,
        needDescription: value.needDescription,
        createdBy: value.createdBy,
        createdDate: value.createdDate,
        validatorNotes: value.validatorNotes,
        estimatedValue: value.estimatedValue,
        validationDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.validationDate)),
        validatedBy: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.validatedBy))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ValidationRecord>): Array<ValidationRecord> {
    return value.map((x)=>from_candid_ValidationRecord_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ValidationRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ValidationRecord): _ValidationRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    validationStatus: string;
    victimId: bigint;
    needType: string;
    needDescription: string;
    createdBy: Principal;
    createdDate: bigint;
    validatorNotes: string;
    estimatedValue: bigint;
    validationDate?: bigint;
    validatedBy?: Principal;
}): {
    id: bigint;
    validationStatus: string;
    victimId: bigint;
    needType: string;
    needDescription: string;
    createdBy: Principal;
    createdDate: bigint;
    validatorNotes: string;
    estimatedValue: bigint;
    validationDate: [] | [bigint];
    validatedBy: [] | [Principal];
} {
    return {
        id: value.id,
        validationStatus: value.validationStatus,
        victimId: value.victimId,
        needType: value.needType,
        needDescription: value.needDescription,
        createdBy: value.createdBy,
        createdDate: value.createdDate,
        validatorNotes: value.validatorNotes,
        estimatedValue: value.estimatedValue,
        validationDate: value.validationDate ? candid_some(value.validationDate) : candid_none(),
        validatedBy: value.validatedBy ? candid_some(value.validatedBy) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
